### ISSUE TITLE
Readme makes false statements about unit tests

### ISSUE THREAD

**Issue by lo1tuma** [abeisgreat/FiltrES.js#3]
In the `README.md` you mentioned that this project has unit tests. Actually the file `filtres-test.js` doesn’t contain a single unit test. The tests are only working with a running elasticsearch instance. That said, I think the right term here is _integration tests_ instead of _unit tests_.

**Comment by abeisgoat** [comment]
I agree, unit tests should be added, but the false statements are long removed so this will be closed.
